[build]
  publish = "public"
  command = "hugo"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

[context.production.environment]
  HUGO_VERSION = "0.41"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.41"
